spring:
  application:
    name: 04-ConnectMultipleDBS
  profiles:
    active:
    - h2

  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/mysql_db
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    h2:
      url: jdbc:h2:mem:h2_db
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update


